// frontend/src/app/shared/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { LucideAngularModule, User, Menu, X } from 'lucide-angular';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterModule, MatButtonModule, LucideAngularModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent {
  isMobileMenuOpen = false;
  readonly UserIcon = User;
  readonly MenuIcon = Menu;
  readonly XIcon = X;
}

<header class="bg-white border-b border-gray-200 sticky top-0 z-40 w-full backdrop-blur-md bg-white/80">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between h-16 items-center">
      <!-- Logo -->
      <div class="flex-shrink-0 flex items-center gap-2 cursor-pointer" routerLink="/">
        <div class="w-8 h-8 rounded-lg bg-brand-600 flex items-center justify-center text-white font-bold">U</div>
        <span class="font-bold text-xl tracking-tight text-gray-900">UNLOST</span>
      </div>

      <!-- Desktop Nav -->
      <nav class="hidden md:flex items-center gap-6">
        <a routerLink="/items" class="text-sm font-medium text-gray-600 hover:text-brand-600 transition-colors">Browse</a>
        <a routerLink="/report-lost" class="text-sm font-medium text-gray-600 hover:text-brand-600 transition-colors">Report Lost</a>
        <a routerLink="/report-found" class="text-sm font-medium text-gray-600 hover:text-brand-600 transition-colors">Report Found</a>
      </nav>

      <!-- User Actions -->
      <div class="hidden md:flex items-center gap-4">
        <!-- Guest -->
        <a mat-button routerLink="/login" class="!font-medium">Sign in</a>
        <a mat-flat-button color="primary" routerLink="/register" class="!font-medium !rounded-full">Get Started</a>

        <!-- Logged In User (Placeholder for now) -->
        <!-- <button mat-icon-button routerLink="/profile">
          <lucide-icon name="user" class="w-5 h-5 text-gray-600"></lucide-icon>
        </button> -->
      </div>

      <!-- Mobile menu button -->
      <div class="flex items-center md:hidden">
        <button mat-icon-button (click)="isMobileMenuOpen = !isMobileMenuOpen">
          <lucide-icon [name]="isMobileMenuOpen ? 'x' : 'menu'" class="w-6 h-6 text-gray-600"></lucide-icon>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile Menu -->
  <div class="md:hidden border-t border-gray-200" *ngIf="isMobileMenuOpen">
    <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3 bg-white">
      <a routerLink="/items" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-brand-600 hover:bg-gray-50" (click)="isMobileMenuOpen = false">Browse</a>
      <a routerLink="/report-lost" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-brand-600 hover:bg-gray-50" (click)="isMobileMenuOpen = false">Report Lost</a>
      <a routerLink="/report-found" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-brand-600 hover:bg-gray-50" (click)="isMobileMenuOpen = false">Report Found</a>
      
      <div class="mt-4 pt-4 border-t border-gray-200">
        <a routerLink="/login" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-brand-600 hover:bg-gray-50" (click)="isMobileMenuOpen = false">Sign in</a>
      </div>
    </div>
  </div>
</header>

// frontend/src/components/Navbar.tsx
import React, { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { Menu, X, LogOut, Search, PlusCircle, Shield, User, Phone } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

const Navbar: React.FC = () => {
  const { user, logout } = useAuth();
  const location = useLocation();
  const [isOpen, setIsOpen] = useState(false);

  const navigation = [
    { name: 'Home', href: '/', icon: Search },
    { name: 'Items', href: '/items', icon: Search },
    { name: 'Report Item', href: '/report', icon: PlusCircle },
    { name: 'Contact', href: '/contact', icon: Phone },
    { name: 'Profile', href: '/profile', icon: User },
  ];

  if (user?.is_admin) {
    navigation.push({ name: 'Admin', href: '/admin', icon: Shield });
  }

  const isActive = (path: string) => {
    if (path === '/') {
      return location.pathname === '/';
    }
    return location.pathname.startsWith(path);
  };

  return (
    <nav className="sticky top-0 z-50 glass-panel border-b border-primary/10 bg-shade-5/80 backdrop-blur-lg">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          <div className="flex items-center">
            <Link to="/" className="flex-shrink-0 flex items-center space-x-2">
              <span className="text-2xl font-extrabold bg-gradient-to-r from-primary via-secondary to-accent bg-clip-text text-transparent tracking-tight font-heading">
                UNLOST
              </span>
            </Link>
          </div>
          
          {/* Desktop Nav */}
          <div className="hidden md:flex items-center space-x-1">
            {navigation.map((item) => (
              <Link
                key={item.name}
                to={item.href}
                className={`relative px-4 py-2 rounded-lg text-sm font-semibold transition-all duration-200 flex items-center space-x-1.5 ${
                  isActive(item.href)
                    ? 'text-primary bg-secondary/10 shadow-inner'
                    : 'text-secondary hover:text-primary hover:bg-secondary/5'
                }`}
              >
                {isActive(item.href) && (
                  <motion.div
                    layoutId="activePill"
                    className="absolute inset-0 bg-secondary/10 rounded-lg -z-10 border border-primary/5"
                    transition={{ type: 'spring', stiffness: 380, damping: 30 }}
                  />
                )}
                <span>{item.name}</span>
              </Link>
            ))}
            
            <div className="h-6 w-px bg-secondary/20 mx-2"></div>
            
            <div className="flex items-center space-x-3">
              <span className="text-xs font-semibold text-secondary border border-primary/10 rounded-full px-3 py-1 bg-white/40">
                {user?.username}
              </span>
              <button
                onClick={logout}
                className="p-2 rounded-lg text-secondary hover:text-rose-500 hover:bg-secondary/5 transition-all duration-200"
                title="Log Out"
              >
                <LogOut className="h-5 w-5" />
              </button>
            </div>
          </div>

          {/* Mobile menu toggle */}
          <div className="md:hidden">
            <button
              onClick={() => setIsOpen(!isOpen)}
              className="inline-flex items-center justify-center p-2 rounded-md text-secondary hover:text-primary hover:bg-secondary/5 focus:outline-none"
            >
              {isOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
            </button>
          </div>
        </div>
      </div>

      {/* Mobile Drawer */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            className="md:hidden border-t border-primary/10 bg-shade-5/95"
          >
            <div className="px-2 pt-2 pb-3 space-y-1 sm:px-3">
              {navigation.map((item) => (
                <Link
                  key={item.name}
                  to={item.href}
                  onClick={() => setIsOpen(false)}
                  className={`flex items-center space-x-3 px-3 py-2 rounded-md text-base font-semibold transition-all ${
                    isActive(item.href)
                      ? 'text-primary bg-secondary/15 shadow-inner'
                      : 'text-secondary hover:text-primary hover:bg-secondary/5'
                  }`}
                >
                  <item.icon className="h-5 w-5" />
                  <span>{item.name}</span>
                </Link>
              ))}
              <div className="border-t border-primary/10 my-2 pt-2 px-3 flex items-center justify-between">
                <span className="text-sm font-semibold text-secondary">{user?.username}</span>
                <button
                  onClick={() => {
                    setIsOpen(false);
                    logout();
                  }}
                  className="flex items-center space-x-1 text-sm font-bold text-rose-500 hover:text-rose-450"
                >
                  <LogOut className="h-4 w-4" />
                  <span>Logout</span>
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </nav>
  );
};

export default Navbar;
